apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: supposed-warbler-dotnet-basic-repository
spec:
  url: https://github.com/prietyc123-qe-org/supposed-warbler-dotnet-basic